spring.application.name=ai-chat-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/aichat_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Security Configuration
security.jwt.secret-key=Test
security.jwt.expiration-time=3600000
spring.datasource.hikari.initialization-fail-timeout=0
